### ISSUE TITLE
Seg fault when running rake

### ISSUE THREAD

**Issue by JoeWeinle** [chef-cookbooks/delivery-cluster#131]
When I ran rake setup I get a seg fault running on Windows.  Here is the error:
https://gist.github.com/JoeWeinle/d9bac3dcbf510988af2d

**Comment by afiune** [comment]
@JoeWeinle Thank you for the feedback! We will try to replicate this issue but we would like to have more information about versions like chefdk, windows, ruby, rake or other things you might thing it is important to know to replicate this and fix it. 

In advance I can tell you that we haven't tested `delivery-cluster` on windows, but we would love to have it working in the future. Thanks for taking a pick! :smile:

**Comment by tas50** [comment]
Closing this out due to lack of response. Feel free to open it back up if you're still seeing this issue
