### ISSUE TITLE
Ability to tag from environment.json file

### ISSUE THREAD

**Issue by psprings** [chef-cookbooks/delivery-cluster#135]
Need to be able to tag an EC2 instance that is provisioned by a Delivery provisioning node in Amazon.

Ex.
"delivery": {
        "flavor": "c3.xlarge",
        "tags": { "Name": "foo",
                    }

**Comment by afiune** [comment]
Created https://github.com/chef/chef-provisioning-aws/issues/252 since this is a functionality that needs to be added to `chef-provisioning-aws`

**Comment by afiune** [comment]
This is possible and could be implemented, look: https://github.com/chef/chef-provisioning-aws#base-resources

**Comment by stephenlauck** [comment]
I will be working with @psprings on a patch to make this happen @afiune .

**Comment by afiune** [comment]
This is on the pipe: https://delivery.chef.co/e/chef/#/organizations/delivery/projects/delivery-cluster/changes/c34e7d17-913d-41e9-8ccf-7309d7616915/status/acceptance

cc/ @mvillis You might be interested on this! :smile:
