### ISSUE TITLE
Remove other package cloud repositories that are not being used.

### ISSUE THREAD

**Issue by afiune** [chef-cookbooks/delivery-cluster#144]
As a user that is consuming the delivery packages from the `current` repository in package cloud and switch over to point to `stable` I need to be sure the system is no longer using the `current` repository so when I run an upgrade I do not pick up packages from the `current` repository.

**Comment by afiune** [comment]
@mjohno @mvillis keep an eye on this.. :smile:

**Comment by mvillis** [comment]
Nice one!!

**Comment by afiune** [comment]
This issue has been solved with this change https://github.com/chef-cookbooks/delivery-cluster/commit/a1dfe9eff638005218669be547a6bc4c0a47b2ea
