### ISSUE TITLE
delivery-cluster fails on cookbook upload

### ISSUE THREAD

**Issue by stephenlauck** [chef-cookbooks/delivery-cluster#147]
When following the README delivery cluster fails on uploading cookbook after building the chef-server.

https://gist.github.com/stephenlauck/875f42d1f4814fd65784

**Comment by afiune** [comment]
Hi @stephenlauck .. Any update gathering the information requested for replication? 

I think I have an idea of what is going ... will wait for your input..

**Comment by afiune** [comment]
@stephenlauck any luck getting those files to replicate the issue?

**Comment by pudge** [comment]
Happened to me too.

```

---- Begin output of knife cookbook upload --all --cookbook-path /home/ubuntu/delivery-cluster/.chef/local-mode-cache/cache/cookbooks --force ----
STDOUT: 
STDERR: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/source/git.rb:188:in `rescue in load_spec_files': https://github.com/chef/chef-provisioning.git (a
t master) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/source/git.rb:185:in `load_spec_files'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/source/path.rb:92:in `local_specs'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/source/git.rb:155:in `specs'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/lazy_specification.rb:53:in `__materialize__'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/spec_set.rb:88:in `block in materialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `map!'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `materialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/definition.rb:132:in `specs'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/definition.rb:177:in `specs_for'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/definition.rb:166:in `requested_specs'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/environment.rb:18:in `requested_specs'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:13:in `setup'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler.rb:122:in `setup'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/setup.rb:17:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
---- End output of knife cookbook upload --all --cookbook-path /home/ubuntu/delivery-cluster/.chef/local-mode-cache/cache/cookbooks --force ----
Ran knife cookbook upload --all --cookbook-path /home/ubuntu/delivery-cluster/.chef/local-mode-cache/cache/cookbooks --force returned 1
[2015-09-22T20:59:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
rake aborted!
Failed executing ChefZero run
/home/ubuntu/delivery-cluster/Rakefile:73:in `chef_zero'
/home/ubuntu/delivery-cluster/Rakefile:317:in `block (2 levels) in <top (required)>'
Tasks: TOP => setup:supermarket => setup:chef_server
(See full trace by running task with --trace)

```

**Comment by tpetchel** [comment]
I was working with @mabrahms to set up a Delivery system on her machine. We ran into what looks like the same issue, but with the EC2 driver.

Output from `rake setup:cluster` is [here](https://gist.github.com/mabrahms-chef/c6346f5626e6165a1373#file-entire-trace-from-last-cluster-run-fail). 

When we tried running `rake destroy:all` to start over, we got [this](https://gist.github.com/mabrahms-chef/c6346f5626e6165a1373#file-rake-destroy-command-fail) error and had to manually release the EC2 instance and clean up the nodes/ directory.

After getting everything cleaned up, we hit the same error after running `rake setup:cluster` again. So we're blocked.

I was able to set things up on EC2 earlier this week, and did not encounter this issue.

**Comment by afiune** [comment]
@tpetchel can I have access to that node? I need to debug and troubleshoot this bug..

**Comment by afiune** [comment]
Issue replicated! I am starting debugging the problem..

**Comment by afiune** [comment]
I've made some deep debugging in how `bundle` interacts internally with `chefdk` and apparently the first one doesn't know how to find the gems that it just installed inside the directory `~/.chefdk/gem/ruby/2.1.0`. I have not found the right solution yet but I have this workaround for anybody that is running into this.

If you export the environment variable `BUNDLE_PATH` pointing to the location I mentioned by running this command:
```
export BUNDLE_PATH=$GEM_HOME
```

You will be fine for now but it is indeed not the delightful path. I will continue researching more!

**Comment by afiune** [comment]
Very rough gist to start a delivery-cluster from scratch.. I will give format but this is the way you can replicate this issue: https://gist.github.com/afiune/add44d18c1d0d2fc38fe

**Comment by afiune** [comment]
The fix is coming!! :smile:  Getting approvals at https://delivery.chef.co/e/chef/#/organizations/delivery/projects/delivery-cluster/changes/1b943e95-e43d-4688-8ac8-db0ccc6c619a/review
