### ISSUE TITLE
Let users create custom `chef-server.rb`

### ISSUE THREAD

**Issue by afiune** [chef-cookbooks/delivery-cluster#157]
As a user I would like to be able to customize my `chef-server.rb` so I can have `ldap` or other things that my enterprise need so I don't manually configure them or they get overwritten.

**Comment by stephenlauck** [comment]
We should leverage the internal Chef Reference Architecture that @jtimberman is working on for this as a test of it's usability.

**Comment by afiune** [comment]
:indeed:

**Comment by jtimberman** [comment]
What you'll want is to make use of the `chef_ingredient` resource's `config` property, and use the `ingredient_config` resource. The `chef-server` cookbook has a very simple example of this use:

https://github.com/chef-cookbooks/chef-server/blob/master/recipes/default.rb

This could just be an attribute, then the consumers can set that to whatever they want, or use the accumulator pattern to add more config to the string in recipes as necessary.

**Comment by afiune** [comment]
That is a great idea. The only thing missing to consider is when you need to have other products enabled like Analytics or Supermarket that modifies the config. I will give this a thought and come with a good solution.. :smile:

**Comment by jtimberman** [comment]
There are helper methods for building the config using an accumulator pattern that modifies the `node.run_state`:

https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/helpers.rb#L246-L257

**Comment by afiune** [comment]
Supported now in master: https://github.com/chef-cookbooks/delivery-cluster/commit/dee2750ce91e611a16a3b1ba107f9abd04c7b06b
