### ISSUE TITLE
builders unable to git clone after rake setup:delivery_build_nodes 

### ISSUE THREAD

**Issue by ghao-ooyala** [chef-cookbooks/delivery-cluster#178]
While trying to replace existing delivery builder node with new builder nodes, running 'rake setup:delivery_build_nodes', a new builder_key is generated and dropped to /var/opt/delivery/workspace/etc/builder_key on each builder nodes; however builder's public key (as see through delivery UI) is not changed; it cause git clone fail on builder nodes;

manually copy public key that match the new builder_key into UI fixed the problem.

**Comment by afiune** [comment]
@ghao-ooyala thank you for reporting this issue. May I ask how you deleted the build-nodes? The only place we generate the builder key is in the `setup_delivery_server.rb` recipe so I wonder how did that run to do this behavior. :smile:

**Comment by taimai** [comment]
Salim: long story but here it goes.  We had 3 builders initially. Then we decided to created 3 new ones having different aws security groups. I edited ooyala.json and replaced the 3 old IPs with the 3 new IPs. I deleted the cache directory on the provisioner, ran setup:delivery_build_nodes then ran setup:cluster. Then we noticed the builders don't all show up when we ran "knife node status."  I ran reconfigure on the server and somehow the 3 builders showed up.
  However Geng noticed that traffic still went to the 3 old builders instead.  That was when I modified ooyala.json again, putting back the 3 old IPs plus the 3 new IPs for a total of 6 builders. I didn't wipe out the cache this time, and just ran the regular builder nodes and cluster setup commands.  Then all the builders couldn't connect to the delivery server anymore.

**Comment by afiune** [comment]
@taimai @ghao-ooyala For curiosity; how did you clean the cache?

**Comment by taimai** [comment]
rm -rf .chef/delivery-cluster-data
rm -rf .chef/delivery-cluster-data-ooyala
chef exec rake maintenance:clean_cache

**Comment by afiune** [comment]
@taimai unfortunately the two `rm` commands is the main cause of this failure. When you ran them you deleted all the data of the cluster that lets the provisioning node manage the infrastructure. 

The proper way to clean the cache is just by running the `rake` command you ran above.

**Comment by taimai** [comment]
I knew that was a bit aggressive :)

**Comment by taimai** [comment]
However I think the main issue here is that if a pub key already exists in the GUI, it won't be overwritten by a new pub key. That was why we keep getting "permission denied" on the git clone command.
