### ISSUE TITLE
Allow running additional cookbooks through delivery-cluster

### ISSUE THREAD

**Issue by galenemery** [chef-cookbooks/delivery-cluster#179]
When standing up a Delivery-cluster with setup:cluster, there are plenty of images that require custom configuration before they're able to finish coming online.

Specifically I ran into an issue where iptables had to be configured to accept inbound connections on the various ports on RHEL boxes.

If we were able to add additional cookbooks to the run_list of nodes, to run before the rest of the config, this would allow users to make whatever config changes they need.

**Comment by afiune** [comment]
@galenemery Thank you this issue. Currently `delivery-cluster` lets you add extra `cookbooks::recipes` to every component on the cluster, look at the **Common Cluster Recipes** [here](https://github.com/chef-cookbooks/delivery-cluster/blob/master/attributes/default.rb#L73,L84) and also Chef-Server and Delivery Server has an extra attribute to add even more at the end of the `run_list`. 
- https://github.com/chef-cookbooks/delivery-cluster/blob/master/attributes/default.rb#L111
- https://github.com/chef-cookbooks/delivery-cluster/blob/master/attributes/default.rb#L169

If this is what you want please close the issue for me :smile:

**Comment by galenemery** [comment]
@afiune does it allow you to run those recipes *before* the rest of the cluster setup?

Specifically I'm looking at rake setup:cluster.  There are times I need to do additional work on the nodes before I can run the rest of the setup recipes (when working with pre-hardened Amazon AMIs for instance).

**Comment by afiune** [comment]
@galenemery yes. the `common_cluster_recipes` will be added at the beginning of the `run_list`

**Comment by afiune** [comment]
Closing this since it is possible to add recipes after and before. :smile:
