### ISSUE TITLE
Allow all provisioning machine/convergence options when standing up clusters

### ISSUE THREAD

**Issue by galenemery** [chef-cookbooks/delivery-cluster#180]
Right now the cookbook only supports the provisioning options specified within the attributes file.  In many environments, other customizations need to be made to either the machine or usually the convergence options in how you bring chef-client up.

**Comment by afiune** [comment]
Closed with https://github.com/chef-cookbooks/delivery-cluster/commit/083956ac1a44991528b849060434990fb156e7f9
