### ISSUE TITLE
No candidate version available for opscode-push-jobs-server

### ISSUE THREAD

**Issue by Seth-Karlo** [chef-cookbooks/delivery-cluster#184]
On CentOS 7.1 fresh install I get the following error:

```
* yum_package[push-server] action install
                             * No candidate version available for opscode-push-jobs-server
                             ================================================================================
                             Error executing action `install` on resource 'yum_package[push-server]'
                             ================================================================================

                             Chef::Exceptions::Package
                             -------------------------
                             No candidate version available for opscode-push-jobs-server
```

I found a similar issue here: https://github.com/chef-cookbooks/chef-ingredient/pull/66/files which seems to relate to package names. Still debugging but wanted to report it.

Thanks!

**Comment by Seth-Karlo** [comment]
This only seems to exist for RHEL5 and 6:
https://downloads.chef.io/push-jobs-server/redhat/

**Comment by afiune** [comment]
@Seth-Karlo Thank you for your feedback! This is currently a known issue in `opscode-push-jobs-server` where we haven't released for EPEL 7+ Systems. This is an issue that belongs to https://github.com/chef/chef-push repo. Do you think you can open it over there? We will appreciate it. :+1:

**Comment by Seth-Karlo** [comment]
Sure thing! I referenced this one so anyone else with the same error can find it.
