### ISSUE TITLE
"delivery review" doesn't report error if delivery failed to push to bitbucket

### ISSUE THREAD

**Issue by taimai** [chef-cookbooks/delivery-cluster#185]
~/repos/chef-delivery/atlantis-logsync $ delivery review
Chef Delivery
Loading configuration from /Users/taimai/repos/chef-delivery/atlantis-logsync
Review for change add-delivery-config targeted for pipeline master

No URL was given, no error indicated. However, on the delivery node, log showed:
current:2015-12-17_18:49:37.06656 18:49:37.057 [error] Failed to push pipeline branch master of project ooyala/appsplat/atlantis-logsync to Bitbucket.

The cause: Chef Delivery role user didn't have write permission on the Bitbucket repo. At the very least, delivery review should indicate an error has occurred.

**Comment by afiune** [comment]
@taimai Thank you for reporting a bug with Delivery. Unfortunately this is not a problem with the `delivery-cluster` cookbook, therefore I will close this issue and reported to the right persons at Chef.
