### ISSUE TITLE
Use newer version of delivery-base so new version of push-jobs-client gets installed

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef-cookbooks/delivery-cluster#199]
I’m using the DCC from master to build a full cluster and my Ubuntu 14.04 build node is getting the old opscode-push-jobs-client 1.0.1 which isn't compatible and leaves my push-jobs-client broken.

I think i’ve traced the problem down to the DCC Berksfile.lock pointing to an old revision of the delivery-base cookbook which sets the `default['push_jobs']['package_url'] = 'http://sales-at-getchef-dot-com.s3.amazonaws.com/opscode-push-jobs-client_1.0.1-1.ubuntu.12.04_amd64.deb'` attribute.

https://github.com/chef-cookbooks/delivery-cluster/blob/master/Berksfile.lock#L10-L12

https://github.com/chef-cookbooks/delivery-base/blob/5f17ebe8fd2be9f345bbfb125084122fe81d4468/attributes/default.rb#L24

Please update the Berksfile.lock to use the latest version of delivery-base cookbook so I can get the correct version of push-jobs-client.

**Comment by afiune** [comment]
@jeremiahsnapp Thank you so much for reporting this!! I am fixing it as we speak.

**Comment by afiune** [comment]
I have removed the tag *InProgress* We will work on this tomorrow.

**Comment by afiune** [comment]
Closed in favor of https://github.com/chef-cookbooks/delivery-cluster/commit/47f69ff5ea9904687e369fd12520096f4a2fa038#diff-8dbb5a65266dafcf8abc624a6e3a2304
