### ISSUE TITLE
delivery moved on to build stage even if pull request is not merged in stash

### ISSUE THREAD

**Issue by ghao-ooyala** [chef-cookbooks/delivery-cluster#210]
Our delivery project are configed to use bitbucket as repo. On Verify stage, click on approve button in delivery suppose to merge pull request in stash; 

but if somehow the pull request get declined in stash due to stash issue, delivery server does not check the status of pull request and continue to build stage etc; 

I would like to have delivery check status of the pull request and continue only if the merge is successful in stash. Thanks.

**Comment by afiune** [comment]
@ghao-ooyala Thank you so much for your feedback!!! The only thing is that this is a direct functionality of Delivery so we can't do anything here in **delivery-cluster**.. I think the best thing to do is to open a new topic at: https://discourse.chef.io

**Comment by ghao-ooyala** [comment]
Salim, that is mailing list; is there a place to open issue with delivery team directly?

**Comment by afiune** [comment]
@ghao-ooyala I dont think to.. either the mailing list or a support ticket... Then Megan will take it from there.. (or just contact her directly 😄 )

**Comment by afiune** [comment]
Another one could the the https://feedback.chef.io
