### ISSUE TITLE
Rake task should remove old vendor cookbooks before vendor again

### ISSUE THREAD

**Issue by chrisduong** [chef-cookbooks/delivery-cluster#212]
Hi,

Every time **Berks** vendor the cookbooks for the `delivery-cluster` cookbook itself, it would re-creating subfolder _cookbooks_ recursively.

We need a job to remove old vendor cookbooks, like

```
msg 'Remove old vendored cookbooks'
system 'rm -rf cookbooks/*'

msg 'Download and vendor the necessary cookbooks locally'
system 'chef exec berks vendor cookbooks'
```

**Comment by afiune** [comment]
@chrisduong Thank you so much for your feedback. Now we clean the cache before we run the prerequisites!!! 👍 https://github.com/chef-cookbooks/delivery-cluster/commit/18eb4739e6cbe101649bae6b3c3174bf595308c5
