### ISSUE TITLE
Integrate delivery cluster with exisiting production chef server 

### ISSUE THREAD

**Issue by ghao-ooyala** [chef-cookbooks/delivery-cluster#213]
Currently, when setup delivery cluster using delivery-cluster cookbook, we provide a newly spin-up instance as future chef server and put name of the instance in environment file under chef-server section; delivery-cluster cookbook will install chef-server on this instance and do all the necessary setups to get a working delivery cluster. After this is done, we get a chef server just for delivery system.

We already have a chef server running in production, a regular use case of chef server;  we would like to use this existing chef server in delivery cluster, instead of getting a seperate chef server just for delivery cluster. 

So we would like to have delivery-cluster cookbook supports a way to embed an existing chef server into delivery system. We saw there is a node['delivery-cluster']['chef-server']['existing'] property in example environment file, and would like to know if that flag is intended for this use case. Thanks.

**Comment by afiune** [comment]
@ghao-ooyala yes! it is intended to be use for the use case you described. If it is a Chef Server HA, you would point it to the back-end vip.

**Comment by afiune** [comment]
@ghao-ooyala I am closing this since I haven't seen anything new about this topic. Let me know if there is anything I can assist you with.
